"""Generate the main results table in the convention used by the LSF literature.

Datasets are column groups with MSE/MAE subcolumns; best per column is bold, second best is
underlined; the last row counts first places. Writes paper/figures/main_table.tex.

usage: python paper/make_main_table.py
Baselines: VisionTS paper (arXiv 2408.17253v4) Table 9 and VisionTS++ (arXiv 2508.04379v3) Table 4.
NOTE 2026-09-17: VisionTS++ Table 4's ETTm2 "avg" row is typeset one column to the left from the
VisionTS column onward, so every ETTm2 average from that row belongs to the NEXT method. The values
below are the corrected assignment, cross-checked against each source's own Average row.
"""
import os

DS = ["ETTm1", "ETTm2", "ETTh1", "ETTh2", "ECL", "Weather"]

# name -> [(mse, mae) per dataset] + ("avg" computed from the source tables, None where unreported)
ROWS = [
    ("\\textbf{Ours}", "vis", [(.352, .369), (.241, .302), (.404, .416), (.335, .376),
                              (.163, .254), (.215, .252)], (.285, .328)),
    ("VisionTS++ (ViT-L)", "vis", [(.354, .369), (.244, .298), (.403, .418), (.327, .365),
                                   (.181, .264), (.226, .243)], (.289, .326)),
    ("VisionTS++ (ViT-B)", "vis", [(.360, .372), (.244, .298), (.402, .416), (.333, .370),
                                   (.184, .265), (.222, .241)], (.291, .327)),
    ("VisionTS", "vis", [(.374, .372), (.282, .321), (.390, .414), (.333, .375),
                         (.207, .294), (.269, .292)], (.309, .345)),
    ("Moirai$_\\mathrm{S}$", "ts", [(.448, .410), (.300, .341), (.400, .424), (.341, .379),
                                    (.233, .320), (.242, .267)], (.327, .357)),
    ("Moirai$_\\mathrm{B}$", "ts", [(.382, .388), (.272, .321), (.434, .439), (.346, .382),
                                    (.188, .274), (.238, .261)], (.310, .344)),
    ("Moirai$_\\mathrm{L}$", "ts", [(.390, .389), (.276, .320), (.510, .469), (.354, .377),
                                    (.188, .273), (.260, .275)], (.330, .350)),
    ("Chronos$_\\mathrm{S}$", "ts", [(.640, .500), (.349, .380), (.545, .472), (.424, .430),
                                     (.220, .284), (.300, .318)], (.413, .397)),
    ("Chronos$_\\mathrm{B}$", "ts", [(.646, .500), (.310, .350), (.591, .468), (.406, .411),
                                     (.215, .279), (.293, .315)], (.410, .387)),
    ("Chronos$_\\mathrm{L}$", "ts", [(.556, .465), (.295, .338), (.589, .466), (.455, .427),
                                     (.204, .274), (.279, .306)], (.396, .379)),
    ("Time-MoE$_\\mathrm{S}$", "ts", [(.394, .416), (.318, .366), (.400, .424), (.367, .404),
                                      None, (.266, .297)], None),
    ("Time-MoE$_\\mathrm{B}$", "ts", [(.376, .406), (.316, .361), (.394, .420), (.405, .415),
                                      None, (.270, .300)], None),
    ("Timer", "ts", [(.487, .457), (.316, .371), (.444, .457), (.358, .407),
                     None, (.304, .331)], None),
    ("TimesFM", "ts", [(.433, .419), (.328, .347), (.473, .444), (.392, .406), None, None], None),
    ("MOMENT", "ts", [(.670, .537), (.317, .366), (.684, .566), (.362, .410),
                      (.765, .687), (.294, .326)], (.515, .482)),
]


def cells(row):
    """-> flat list of 14 values (or None): 6 datasets x (mse, mae) + avg mse, avg mae."""
    out = []
    for v in row[2]:
        out += [None, None] if v is None else [v[0], v[1]]
    out += [None, None] if row[3] is None else [row[3][0], row[3][1]]
    return out


def main(out="paper/figures/main_table.tex"):
    table = [cells(r) for r in ROWS]
    ncol = len(table[0])
    best, second = [], []
    for c in range(ncol):
        vals = sorted(v for v in (row[c] for row in table) if v is not None)
        best.append(vals[0] if vals else None)
        second.append(next((v for v in vals if v > vals[0]), None) if vals else None)

    def fmt(v, c):
        if v is None:
            return "n/r"
        s = f"{v:.3f}"
        if v == best[c]:
            return "\\textbf{" + s + "}"
        if second[c] is not None and v == second[c]:
            return "\\underline{" + s + "}"
        return s

    firsts = [sum(1 for c in range(12) if row[c] is not None and row[c] == best[c]) for row in table]

    L = []
    L.append("% generated by paper/make_main_table.py -- do not edit by hand")
    L.append("\\begin{table}[t]")
    L.append("\\caption{Zero-shot long-sequence forecasting. Each entry averages the four horizons "
             "$H\\in\\{96,192,336,720\\}$; MSE and MAE are computed on standardised values. Our model "
             "uses one checkpoint and one inference rule for all 24 cells. Baselines are quoted from "
             "\\citet{visiontspp} and \\citet{visionts}; `n/r' means the source does not report that "
             "dataset. \\textbf{Bold}: best. \\underline{Underlined}: second best. The last column counts "
             "first places over the twelve dataset columns.}")
    L.append("\\label{tab:main}")
    L.append("\\begin{center}")
    L.append("\\setlength{\\tabcolsep}{3pt}")
    L.append("\\scriptsize")
    L.append("\\begin{tabular}{l" + "cc" * 7 + "c}")
    L.append("\\toprule")
    L.append("\\multirow{2}{*}{Model} & " + " & ".join(
        f"\\multicolumn{{2}}{{c}}{{{d}}}" for d in DS + ["\\textbf{Avg}"]) +
        " & \\multirow{2}{*}{1\\textsuperscript{st}} \\\\")
    L.append(" ".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(7)))
    L.append(" & " + " & ".join(["MSE", "MAE"] * 7) + " & \\\\")
    L.append("\\midrule")
    prev = ROWS[0][1]
    for row, vals, nf in zip(ROWS, table, firsts):
        if row[1] != prev:
            L.append("\\midrule")
            prev = row[1]
        L.append(row[0] + " & " + " & ".join(fmt(v, c) for c, v in enumerate(vals)) +
                 f" & {nf if nf else '0'} \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{center}")
    L.append("\\end{table}")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", out)
    print("first places:", {r[0]: n for r, n in zip(ROWS, firsts) if n})


if __name__ == "__main__":
    main()
