"""Generate the per-cell head-to-head appendix table.

Ours: recomputed from the raw result JSONs of the 60k seed-0 run (tag st_f32_savl_l2sp_v2_60k),
merging origin-range parts by summing se/ae/cnt as in pilot/final_bigtable.py.
VisionTS: arXiv 2408.17253v4 Table 9.
VisionTS++ base: arXiv 2508.04379v3 Table 4 (Appendix C.2).

usage: python paper/make_perhorizon_table.py   ->  paper/figures/perhorizon_table.tex
"""
import os

H = [96, 192, 336, 720]
# dataset -> (ours, visionts, visionts++ base); each a list of (mse, mae) per horizon
DATA = {
 "ETTm1": ([(.2915,.3317),(.3321,.3568),(.3625,.3771),(.4231,.4086)],
           [(.341,.347),(.360,.360),(.377,.374),(.416,.405)],
           [(.316,.343),(.347,.362),(.368,.379),(.408,.405)]),
 "ETTm2": ([(.1600,.2446),(.2141,.2827),(.2636,.3183),(.3279,.3622)],
           [(.228,.282),(.262,.305),(.293,.328),(.343,.370)],
           [(.169,.248),(.216,.279),(.260,.308),(.330,.358)]),
 "ETTh1": ([(.3519,.3800),(.3962,.4082),(.4238,.4254),(.4460,.4494)],
           [(.353,.383),(.392,.410),(.407,.423),(.406,.441)],
           [(.369,.392),(.399,.412),(.415,.421),(.424,.437)]),
 "ETTh2": ([(.2663,.3243),(.3335,.3692),(.3611,.3948),(.3788,.4152)],
           [(.271,.328),(.328,.367),(.345,.381),(.388,.422)],
           [(.277,.326),(.333,.362),(.350,.384),(.370,.409)]),
 "ECL":   ([(.1277,.2194),(.1476,.2393),(.1698,.2620),(.2071,.2938)],
           [(.177,.266),(.188,.277),(.207,.296),(.256,.337)],
           [(.152,.237),(.168,.252),(.186,.269),(.228,.303)]),
 "Weather":([(.1388,.1833),(.1811,.2262),(.2316,.2664),(.3080,.3306)],
           [(.220,.257),(.244,.275),(.280,.299),(.330,.337)],
           [(.145,.179),(.187,.219),(.240,.258),(.317,.308)]),
}


def main(out="paper/figures/perhorizon_table.tex"):
    L = ["% generated by paper/make_perhorizon_table.py -- do not edit by hand",
         "\\begin{table}[h]",
         "\\caption{Per-cell comparison against the two baselines that publish per-horizon results on "
         "this protocol: VisionTS (arXiv 2408.17253v4, Table 9) and VisionTS++ base (arXiv "
         "2508.04379v3, Table 4). \\textbf{Bold}: best of the three in that column group. Counts are "
         "given in the text.}",
         "\\label{tab:perhorizon-vts}", "\\begin{center}",
         "\\setlength{\\tabcolsep}{3.4pt}", "\\footnotesize",
         "\\begin{tabular}{llcccccc}", "\\toprule",
         " & & \\multicolumn{3}{c}{MSE} & \\multicolumn{3}{c}{MAE} \\\\",
         "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8}",
         "Dataset & $H$ & Ours & VisionTS & VisionTS++$_\\mathrm{B}$ & Ours & VisionTS & VisionTS++$_\\mathrm{B}$ \\\\",
         "\\midrule"]
    wins = {"mse": [0, 0, 0], "mae": [0, 0, 0]}
    for ds, (a, b, c) in DATA.items():
        for i, h in enumerate(H):
            row = [f"{ds if i == 0 else ''}", f"{h}"]
            for m in (0, 1):
                vals = [a[i][m], b[i][m], c[i][m]]
                best = min(vals)
                wins["mse" if m == 0 else "mae"][vals.index(best)] += 1
                row += [("\\textbf{%.3f}" % v) if v == best else ("%.3f" % v) for v in vals]
            L.append(" & ".join(row) + " \\\\")
        L.append("\\midrule" if ds != "Weather" else "\\bottomrule")
    L += ["\\end{tabular}", "\\end{center}", "\\end{table}"]
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", out)
    print("best-of-three counts (ours, VisionTS, VisionTS++ base):",
          "MSE", wins["mse"], " MAE", wins["mae"])
    for name, other in (("VisionTS", 1), ("VisionTS++ base", 2)):
        for m, lab in ((0, "MSE"), (1, "MAE")):
            w = sum(1 for ds in DATA for i in range(4)
                    if DATA[ds][0][i][m] < DATA[ds][other][i][m])
            print(f"  head-to-head vs {name} on {lab}: {w}/24")


if __name__ == "__main__":
    main()
